<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = \Faker\Factory::create('id_ID');

        $comic_books = array(
            array(
                'name'         => 'Jujutsu Kaisen 01',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'price'        => 40000,
                'image'        => 'jujutsu-kaisen-01.jpg',
                'author_id'    => 1,
                'rating'       => 4.7,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Demon Slayer: Kimetsu No Yaiba 01',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'price'        => 40000,
                'image'        => 'kimetsu-no-yaiba-01.jpg',
                'author_id'    => 2,
                'rating'       => 4.9,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Detektif Conan 96',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'price'        => 25000,
                'image'        => 'detektif-conan-96.jpg',
                'author_id'    => 3,
                'rating'       => 4.5,
                'discount'     => null,
                'ebook'        => true,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Fairy Tail 100 Years Quest 01',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'price'        => 28000,
                'image'        => 'fairy-tail-100-years-quest-01.jpg',
                'author_id'    => 4,
                'rating'       => 4.7,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Haikyu!!: Fly High! Volleyball! 21',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'haikyuu-21.jpg',
                'price'        => 35000,
                'author_id'    => 5,
                'rating'       => 5.0,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Jujutsu Kaisen 02',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'price'        => 40000,
                'image'        => 'jujutsu-kaisen-02.jpg',
                'author_id'    => 1,
                'rating'       => 4.9,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Demon Slayer: Kimetsu No Yaiba 02',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'price'        => 40000,
                'image'        => 'kimetsu-no-yaiba-02.jpg',
                'author_id'    => 2,
                'rating'       => 4.8,
                'discount'     => 10000,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Detektif Conan 97',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'price'        => 25000,
                'image'        => 'detektif-conan-97.jpg',
                'author_id'    => 3,
                'rating'       => 3.7,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Fairy Tail 100 Years Quest 02',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'price'        => 28000,
                'image'        => 'fairy-tail-100-years-quest-02.jpg',
                'author_id'    => 4,
                'rating'       => 4.1,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Haikyu!!: Fly High! Volleyball! 22',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'haikyuu-22.jpg',
                'price'        => 35000,
                'author_id'    => 5,
                'rating'       => 4.8,
                'discount'     => 5000,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Bicara Itu Ada Seninya',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'bicara-itu-ada-seninya.jpg',
                'price'        => 67000,
                'author_id'    => 6,
                'rating'       => 3.7,
                'discount'     => 2000,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Bahasa Korea Untuk Pemula : Let`S Talk And Practice',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'bahasa-korea-untuk-pemula-lets-talk-and-practice.jpg',
                'price'        => 69000,
                'author_id'    => 7,
                'rating'       => 3.7,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Kamus Lengkap Bahasa Jepang|Diramoti Benedict',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'kamus-lengkap-bahasa-jepang-diramoti-benedict.jpg',
                'price'        => 78000,
                'author_id'    => 8,
                'rating'       => 4.3,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Juz 11 - 20 : Al-Quran Tulis Metode Follow The Lin',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'juz-11-20-al-quran-tulis-metode-follow-the-lin.jpg',
                'price'        => 78000,
                'author_id'    => 9,
                'rating'       => 4.5,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Kitab Lengkap Grammar : Jurus Ampuh Kuasai Grammar',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'kitab-lengkap-grammar-jurus-ampuh-kuasai-grammar.jpg',
                'price'        => 49500,
                'author_id'    => 10,
                'rating'       => 4.5,
                'discount'     => 5000,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Hello! Easy English: Bahasa Inggris Itu Mudah!',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'hello-easy-english-bahasa-inggris-itu-mudah.jpg',
                'price'        => 29500,
                'author_id'    => 11,
                'rating'       => 4.5,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Sukses Belajar Bahasa Jepang',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'sukses-belajar-bahasa-jepang.jpg',
                'price'        => 39500,
                'author_id'    => 12,
                'rating'       => 4.9,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Filosofi Teras Filsafat Yunani-Romawi Kuno Untuk Mental Tangguh Masa Kini',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'filosofi-teras-filsafat-yunani-romawi-kuno-untuk-mental-tangguh-masa-kini.jpg',
                'price'        => 98000,
                'author_id'    => 13,
                'rating'       => 4.6,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Kamus Geografi Edisi Tematik Dan Visual',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'kamus-geografis-edisi-tematik-dan-visual.jpg',
                'price'        => 245000,
                'author_id'    => 14,
                'rating'       => 4.6,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Top Score Jlpt-Nat Japanese Language Proficiecy Test Nihongo',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'top-score-jlpt-nat-japanese-language-proficiecy-tedy-nihongo.jpg',
                'price'        => 160000,
                'author_id'    => 15,
                'rating'       => 4.6,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Bahasa Korea Untuk Kpopers 1',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'bahasa-korea-untuk-kpopers-1.jpg',
                'price'        => 30000,
                'author_id'    => 16,
                'rating'       => 4.2,
                'discount'     => 2000,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Kamus Bahasa Jerman',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'kamus-bahasa-jerman-langenscheidt.jpg',
                'price'        => 315000,
                'author_id'    => 17,
                'rating'       => 4.2,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Al Quran & Terjemah A4',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'al-quran-&-terjemah-a4.jpg',
                'price'        => 88000,
                'author_id'    => 17,
                'rating'       => 4.2,
                'discount'     => 13200,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Homemade Tempe: Bikin Sendiri Tempe Sehatmu',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'homemade-tempe-biki-sendiri-tempe-sehatmu.jpg',
                'price'        => 48000,
                'author_id'    => 17,
                'rating'       => 4.3,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Tintin Rayner Home Baking',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'tintin-rayner-home-baking.jpg',
                'price'        => 168000,
                'author_id'    => 18,
                'rating'       => 4.9,
                'discount'     => null,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Cooking Baking For Dummies: Sweet & Savory Cookies',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'cooking-baking-for-dummies-sweet-&-savory-cookies.jpg',
                'price'        => 79840,
                'author_id'    => 19,
                'rating'       => 3.3,
                'discount'     => 14800,
                'ebook'        => false,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Resep Simple Frida 2',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'resep-simple-frida-2.jpg',
                'price'        => 79840,
                'author_id'    => 20,
                'rating'       => 4.2,
                'discount'     => 13500,
                'ebook'        => true,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Andin`S Kitchen Masak Tanpa Mumet',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'andins-kitchen-masak-tanpa-mumet.jpg',
                'price'        => 155000,
                'author_id'    => 21,
                'rating'       => 4.9,
                'discount'     => null,
                'ebook'        => true,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => '80 Resep Masakan Nusantara Populer ala Cheche Kitchen Hits di Instagram',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => '80-resep-masakan-nusantara-populer-ala-cheche-kitchen-hits-di-instagrams.jpg',
                'price'        => 145000,
                'author_id'    => 22,
                'rating'       => 5.0,
                'discount'     => null,
                'ebook'        => true,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
            array(
                'name'         => 'Chinese Restaurant At Home Ala Miss Lee',
                'isbn'         => $faker->unique()->numerify('978##########'),
                'image'        => 'chinese-restaurant-at-home-ala-miss-lee.jpg',
                'price'        => 98000,
                'author_id'    => 23,
                'rating'       => 4.2,
                'discount'     => null,
                'ebook'        => true,
                'pages'        => $faker->numberBetween(200, 400),
                'release_date' => '2021-01-28',
                'publisher'    => 'Elek Media Komputindo',
                'subtitle'     => 'Indonesia',
                'weight'       => 300,
                'width'        => 12.0,
                'height'       => 18.0,
            ),
        );

        foreach ($comic_books as $book) {
            Book::create(
                array(
                    'isbn'         => $book['isbn'],
                    'name'         => $book['name'],
                    'price'        => $book['price'],
                    'image'        => $book['image'],
                    'author_id'    => $book['author_id'],
                    'rating'       => $book['rating'],
                    'discount'     => $book['discount'],
                    'ebook'        => $book['ebook'],
                    'pages'        => $book['pages'],
                    'release_date' => $book['release_date'],
                    'publisher'    => $book['publisher'],
                    'subtitle'     => $book['subtitle'],
                    'weight'       => $book['weight'],
                    'width'        => $book['width'],
                    'height'       => $book['height'],
                )
            );
        }

        // Book::create(
        //     array(
        //         'name'        => 'Kimetsu Mugen Train',
        //         'price'       => 23400,
        //         'image'       => 'kimetsu-mugen-train.jpg',
        //         'author_id'   => 2,
        //     )
        // );
    }
}
